version: '3'
services:
    web:
        build:
            context: ./
            dockerfile: .docker/nginx/Dockerfile
        ports:
            - 9001:80
        links:
            - lumen-auth
        volumes:
            - ./source-code:/var/www/html/source-code
    lumen-auth:
        build:
            context: ./
            dockerfile: .docker/php/Dockerfile
        volumes:
            - ./source-code:/var/www/html/source-code
        environment:
            LOG_CHANNEL: single
            DB_CONNECTION: mongodb
            DB_HOST: "${DB_HOST}"
            DB_PORT: "${DB_PORT}"
            DB_MAIN_DATABASE: "${DB_MAIN_DATABASE}"
            DB_AUTH_DATABASE: "{$DB_AUTH_DATABASE}"
            DB_USERNAME: "${DB_USERNAME}"
            DB_PASSWORD: "${DB_PASSWORD}"